import React from 'react';
import { Printer } from 'lucide-react';
import { Button } from '@/components/ui';

interface PrintableReportContainerProps {
  academyName: string;
  title: string;
  subtitle?: string;
  generatedAt?: string;
  children: React.ReactNode;
  onPrint?: () => void;
  actions?: React.ReactNode;
}

export function PrintableReportContainer({
  academyName,
  title,
  subtitle,
  generatedAt,
  children,
  onPrint,
  actions,
}: PrintableReportContainerProps) {
  const handlePrint = () => {
    if (onPrint) {
      onPrint();
    } else {
      window.print();
    }
  };

  return (
    <div className="space-y-6">
      {/* Top Action Bar (hidden in print) */}
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <div>
          <h2 className="text-fg text-xl font-black tracking-tight">{title}</h2>
          {subtitle && <p className="text-fg-muted text-xs">{subtitle}</p>}
        </div>
        <div className="flex items-center gap-2">
          {actions}
          <Button
            type="button"
            variant="secondary"
            size="sm"
            onClick={handlePrint}
            className="flex items-center gap-1.5"
          >
            <Printer className="h-4 w-4" />
            <span>Print / Save PDF</span>
          </Button>
        </div>
      </div>

      {/* Printable Sheet */}
      <div className="border-border-subtle bg-surface rounded-2xl border p-4 shadow-sm md:p-6 print:border-none print:bg-white print:p-0 print:text-black print:shadow-none">
        {/* Printable Header */}
        <div className="border-border-subtle mb-6 flex items-start justify-between border-b pb-4 print:border-black/20">
          <div>
            <span className="text-primary text-xs font-black tracking-wider uppercase print:text-black">
              {academyName}
            </span>
            <h1 className="text-fg text-2xl font-black tracking-tight print:text-black">{title}</h1>
            {subtitle && (
              <p className="text-fg-muted mt-0.5 text-xs font-medium print:text-black/70">
                {subtitle}
              </p>
            )}
          </div>
          <div className="text-right">
            <span className="text-fg-muted block text-[10px] font-bold tracking-wider uppercase print:text-black/60">
              Official Academy Report
            </span>
            <span className="text-fg text-xs font-medium print:text-black">
              {generatedAt || new Date().toISOString().split('T')[0]}
            </span>
          </div>
        </div>

        {/* Report Content Body */}
        <div>{children}</div>

        {/* Printable Footer */}
        <div className="border-border-subtle mt-8 hidden border-t pt-4 text-xs text-black/60 print:block">
          <div className="flex items-center justify-between">
            <span>Generated by Cricket Academy Platform</span>
            <div className="flex gap-12 text-right">
              <span>Coach / Admin Signature: _______________________</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
